INSERT INTO players (nick, email, password) VALUES ("tytus", "tytus@wp.pl", "tytus123")
INSERT INTO players (nick, email, password)) VALUES ("romek", "romuald23@gmail.com", "RomanOwicz333")
INSERT INTO players (nick, email, password) VALUES ("Agatka", "AgAtA69@wp.pl", "x123x321x")
INSERT INTO players (nick, email, password) VALUES ("Bonio55", "Bonifacy.Okr@gmail.com", "Mastermind")
INSERT INTO villages (player id, name , x, z) VALUES ("1", "tytus")
INSERT INTO villages (player id, name , x, z) VALUES ("2", "romek")
INSERT INTO villages (player id, name , x, z) VALUES ("3", "Agatka")
INSERT INTO villages (player id, name , x, z) VALUES ("4", "Bonio55")
INSERT INTO resources (drewno, glina, żelazo, kamień) VALUES ("500","500","500","500")
INSERT INTO buildings (dom z gliny, huta żelaza, hata drwala) VALUES ("1","0","0")
INSERT INTO troopers (łucznik, miecznik, kusznik, rycerz) VALUES ("0","1","0","2")
