-- MySQL Script generated by MySQL Workbench
-- Wed Sep 28 15:49:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `reasarces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reasarces` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `troops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `troops` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `damage` VARCHAR(45) NULL,
  `defence` VARCHAR(45) NULL,
  `troopscoldistance damage` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buildings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buildings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `players` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nick` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `villages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `villages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `x` VARCHAR(45) NULL,
  `y` VARCHAR(45) NULL,
  `players_id` INT NOT NULL,
  PRIMARY KEY (`id`, `players_id`),
  CONSTRAINT `fk_villages_players1`
    FOREIGN KEY (`players_id`)
    REFERENCES `players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `villages_has_reasarces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `villages_has_reasarces` (
  `villages_id` INT NOT NULL,
  `reasarces_id` INT NOT NULL,
  PRIMARY KEY (`villages_id`, `reasarces_id`),
  CONSTRAINT `fk_villages_has_reasarces_villages`
    FOREIGN KEY (`villages_id`)
    REFERENCES `villages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_villages_has_reasarces_reasarces1`
    FOREIGN KEY (`reasarces_id`)
    REFERENCES `reasarces` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `villages_has_buildings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `villages_has_buildings` (
  `villages_id` INT NOT NULL,
  `villages_players_id` INT NOT NULL,
  `buildings_id` INT NOT NULL,
  PRIMARY KEY (`villages_id`, `villages_players_id`, `buildings_id`),
  CONSTRAINT `fk_villages_has_buildings_villages1`
    FOREIGN KEY (`villages_id` , `villages_players_id`)
    REFERENCES `villages` (`id` , `players_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_villages_has_buildings_buildings1`
    FOREIGN KEY (`buildings_id`)
    REFERENCES `buildings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `troops_has_villages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `troops_has_villages` (
  `troops_id` INT NOT NULL,
  `villages_id` INT NOT NULL,
  `villages_players_id` INT NOT NULL,
  PRIMARY KEY (`troops_id`, `villages_id`, `villages_players_id`),
  CONSTRAINT `fk_troops_has_villages_troops1`
    FOREIGN KEY (`troops_id`)
    REFERENCES `troops` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_troops_has_villages_villages1`
    FOREIGN KEY (`villages_id` , `villages_players_id`)
    REFERENCES `villages` (`id` , `players_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
